[package]
name = "gpgme-sys"
version = "0.6.1"
authors = ["John Schug <john.ips.schug@gmail.com>"]
license = "LGPL-2.1"
repository = "https://github.com/johnschug/rust-gpgme"
documentation = "https://docs.rs/gpgme-sys"
categories = ["external-ffi-bindings"]
keywords = ["gpg", "gpgme", "crypto", "cryptography"]
description = "Raw bindings for gpgme"
links = "gpgme"
build = "build.rs"

[badges]
travis-ci = { repository = "johnschug/rust-gpgme" }
maintenance = { status = "experimental" }

[lib]
name = "gpgme_sys"
path = "lib.rs"

[build-dependencies]
gcc = "0.3"
semver = "0.9"

[dependencies]
libc = "0.2"
libgpg-error-sys = "0.3"
