[package]
name = "gpgme-sys"
description = "Raw bindings for gpgme"
repository = "https://github.com/johnschug/rust-gpgme"
version = "0.2.0"
authors = ["John Schug <john.ips.schug@gmail.com>"]
license = "LGPL-2.1"
keywords = ["gpg", "gpgme", "crypto", "cryptography"]
links = "gpgme"
build = "build.rs"

[lib]
name = "gpgme_sys"
path = "lib.rs"

[dependencies]
libc = "0.1"
libgpg-error-sys = "0.1"
