[package]
name = "gpgme-sys"
version = "0.8.0"
authors = ["John Schug <john.ips.schug@gmail.com>"]
license = "LGPL-2.1"
repository = "https://github.com/gpg-rs/gpgme/gpgme-sys"
documentation = "https://docs.rs/gpgme-sys"
categories = ["external-ffi-bindings"]
keywords = ["gpg", "gpgme", "crypto", "cryptography"]
description = "Raw bindings for gpgme"
links = "gpgme"
build = "build.rs"

[badges]
travis-ci = { repository = "gpg-rs/gpgme" }
maintenance = { status = "experimental" }

[lib]
name = "gpgme_sys"
path = "lib.rs"

[features]
default = ["bundled"]
bundled = ["libgpg-error-sys/bundled"]

[build-dependencies]
cc = "1.0.2"

[dependencies]
libc = "0.2"
libgpg-error-sys = { version = "0.4", default-features = false }
