[package]
name = "gpgme-sys"
version = "0.6.0"
authors = ["John Schug <john.ips.schug@gmail.com>"]
repository = "https://github.com/johnschug/rust-gpgme"
license = "LGPL-2.1"
keywords = ["gpg", "gpgme", "crypto", "cryptography"]
categories = ["external-ffi-bindings"]
description = "Raw bindings for gpgme"
links = "gpgme"
build = "build.rs"

[badges]
travis-ci = { repository = "johnschug/rust-gpgme" }

[lib]
name = "gpgme_sys"
path = "lib.rs"

[features]
default = ["v1_9_0"]
v1_3_0 = []
v1_3_1 = ["v1_3_0"]
v1_4_0 = ["v1_3_1"]
v1_4_2 = ["v1_4_0"]
v1_4_3 = ["v1_4_2"]
v1_5_0 = ["v1_4_3"]
v1_5_1 = ["v1_5_0"]
v1_6_0 = ["v1_5_1"]
v1_7_0 = ["v1_6_0"]
v1_7_1 = ["v1_7_0"]
v1_8_0 = ["v1_7_1"]
v1_9_0 = ["v1_8_0"]

[build-dependencies]
cfg-if = "0.1"
gcc = "0.3"

[dependencies]
libc = "0.2"
libgpg-error-sys = "0.2"
