language: rust
cache: cargo
env:
  global:
    - GPGME_DEBUG=9
matrix:
  include:
    - addons:
        apt:
          packages:
            - libgpg-error-dev
            - libgpgme11-dev
    - rust: nightly
      addons:
        apt:
          packages:
            - libgpg-error-dev
            - libgpgme11-dev
      env:
        - CARGO_FLAGS="--features nightly"
    - os: osx
      addons:
        homebrew:
          update: true
          packages:
            - gpgme
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - gpg --version || true
  - gpg2 --version || true
  - gpg-agent --version || true
script:
  - cargo build --verbose --verbose $CARGO_FLAGS
  - cargo test --verbose --no-fail-fast $CARGO_FLAGS
  - cargo run -p systest $CARGO_FLAGS || true
branches:
  except:
    - /^v[0-9]/
notifications:
  email:
    on_success: never
