language: rust
cache: cargo
matrix:
  include:
    - os: osx
      before_install:
        - brew install gettext
        - brew link gettext --force
      after_script:
        - otool -L target/debug/target/debug/examples/encrypt
    - os: linux
      addons:
        apt:
          packages:
            - libgpgme11-dev
    - os: linux
      env:
        - GETTEXT_VERSION=0.19.8.1
      before_install:
        - curl -sL https://ftp.gnu.org/gnu/gettext/gettext-${GETTEXT_VERSION}.tar.gz -o gettext-${GETTEXT_VERSION}.tar.gz
        - tar -xf gettext-${GETTEXT_VERSION}.tar.gz
        - pushd gettext-${GETTEXT_VERSION}
        - ./configure --without-emacs --disable-java --disable-csharp --disable-c++ --enable-fast-install --prefix=${HOME}/.local >/dev/null
        - make -j2 install >/dev/null
        - popd
        - export PATH=${HOME}/.local/bin:$PATH
        - export LD_LIBRARY_PATH=${HOME}/.local/lib:$LD_LIBRARY_PATH
    - os: linux
      env:
        - GETTEXT_VERSION=0.19.8.1
      addons:
        apt:
          packages:
            - musl-tools
      before_install:
        - curl -sL https://ftp.gnu.org/gnu/gettext/gettext-${GETTEXT_VERSION}.tar.gz -o gettext-${GETTEXT_VERSION}.tar.gz
        - tar -xf gettext-${GETTEXT_VERSION}.tar.gz
        - pushd gettext-${GETTEXT_VERSION}
        - ./configure --without-emacs --disable-java --disable-csharp --disable-c++ --enable-fast-install --prefix=${HOME}/.local >/dev/null
        - make -j2 install >/dev/null
        - popd
        - export PATH=${HOME}/.local/bin:$PATH
        - export LD_LIBRARY_PATH=${HOME}/.local/lib:$LD_LIBRARY_PATH
        - rustup target add x86_64-unknown-linux-musl
      script:
        - cargo build --target=x86_64-unknown-linux-musl --verbose --verbose
        - cargo test --target=x86_64-unknown-linux-musl --verbose --verbose
      after_script:
        - objdump -T target/x86_64-unknown-linux-musl/examples/encrypt
before_script:
  - gpg --version || true
  - gpg2 --version || true
  - gpg-agent --version || true
script:
  - cargo build --verbose --verbose
  - cargo test --no-fail-fast
  - cargo doc
after_script:
  - ldd target/debug/examples/encrypt
env:
  global:
    - GPGME_DEBUG=9
branches:
  except:
    - /^v[0-9]/
notifications:
  email:
    on_success: never
