language: rust
cache: cargo
matrix:
  include:
    - os: osx
      before_install:
        - brew install gettext
        - brew link gettext --force
      after_script:
        - otool -L target/debug/examples/encrypt
    - env:
        - CARGO_FLAGS=--no-default-features
      addons:
        apt:
          packages:
            - libgpgme11-dev
    - env:
        - GETTEXT_VERSION=0.19.8.1
      before_install:
        - .travis/install-gettext.sh $GETTEXT_VERSION
    - env:
        - CARGO_FLAGS="--target x86_64-unknown-linux-musl"
        - GETTEXT_VERSION=0.19.8.1
      addons:
        apt:
          packages:
            - musl-tools
      before_install:
        - .travis/install-gettext.sh $GETTEXT_VERSION
        - rustup target add x86_64-unknown-linux-musl
      after_script:
        - objdump -T target/x86_64-unknown-linux-musl/debug/examples/encrypt
    - rust: nightly
      env:
        - CARGO_FLAGS="--features nightly"
        - GETTEXT_VERSION=0.19.8.1
      before_install:
        - .travis/install-gettext.sh $GETTEXT_VERSION
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - gpg --version || true
  - gpg2 --version || true
  - gpg-agent --version || true
script:
  - cargo build --verbose --verbose $CARGO_FLAGS
  - cargo test --verbose --no-fail-fast $CARGO_FLAGS
after_script:
  - ldd target/debug/examples/encrypt
env:
  global:
    - GPGME_DEBUG=9
branches:
  except:
    - /^v[0-9]/
notifications:
  email:
    on_success: never
