language: rust
cache: cargo
os:
  - linux
  - osx
before_script:
  - gpg --version || true
  - gpg2 --version || true
  - gpg-agent --version || true
script:
  - cargo build --verbose --verbose
  - cargo test --no-fail-fast
  - cargo doc
env:
  global:
    - GPGME_DEBUG=9
branches:
  except:
    - /^v[0-9]/
