[package]
name = "gpgme"
description = "GPGme bindings for Rust"
repository = "https://github.com/johnschug/rust-gpgme"
documentation = "https://johnschug.github.io/rust-gpgme"
version = "0.3.0"
authors = ["John Schug <john.ips.schug@gmail.com>"]
license = "LGPL-2.1"
keywords = ["gpg", "gpgme", "crypto", "cryptography"]

[dependencies]
libc = "0.1"
bitflags = "0.2"
enum_primitive = "*"
lazy_static = "0.1"

[dependencies.gpgme-sys]
path = "gpgme-sys"
version = "0.2.0"

[dev-dependencies]
getopts = "0.2"
tempdir = "0.3"

[[bin]]
name = "pinentry"
test = false

[[test]]
name = "keylist"

[[test]]
name = "symmetric"

[[test]]
name = "encrypt"

[[test]]
name = "decrypt"

[[test]]
name = "sign"

[[test]]
name = "signers"

[[test]]
name = "notations"

[[test]]
name = "verify"

[[test]]
name = "encrypt_sign"

[[test]]
name = "decrypt_verify"

[[test]]
name = "import"

[[test]]
name = "export"
