[package]
name = "gpgme"
version = "0.6.0"
authors = ["John Schug <john.ips.schug@gmail.com>"]
repository = "https://github.com/johnschug/rust-gpgme"
license = "LGPL-2.1"
documentation = "https://johnschug.github.io/rust-gpgme"
keywords = ["gpg", "gpgme", "crypto", "cryptography"]
categories = ["api-bindings"]
description = "GPGme bindings for Rust"

[badges]
travis-ci = { repository = "johnschug/rust-gpgme" }

[features]
default = ["v1_9_0"]
v1_3_0 = []
v1_3_1 = ["v1_3_0", "gpgme-sys/v1_3_1"]
v1_4_0 = ["v1_3_1", "gpgme-sys/v1_4_0"]
v1_4_2 = ["v1_4_0", "gpgme-sys/v1_4_2"]
v1_4_3 = ["v1_4_2", "gpgme-sys/v1_4_3"]
v1_5_0 = ["v1_4_3", "gpgme-sys/v1_5_0"]
v1_5_1 = ["v1_5_0", "gpgme-sys/v1_5_1"]
v1_6_0 = ["v1_5_1", "gpgme-sys/v1_6_0"]
v1_7_0 = ["v1_6_0", "gpgme-sys/v1_7_0"]
v1_7_1 = ["v1_7_0", "gpgme-sys/v1_7_1"]
v1_8_0 = ["v1_7_1", "gpgme-sys/v1_8_0"]
v1_9_0 = ["v1_8_0", "gpgme-sys/v1_9_0"]
nightly = ["lazy_static/nightly"]

[dependencies]
libc = "0.2"
cfg-if = "0.1"
bitflags = "0.8"
lazy_static = "0.2"
conv = "0.3"
gpg-error = "0.2"
gpgme-sys = { path = "gpgme-sys", version = "0.6.0", default-features = false }

[dev-dependencies]
getopts = "0.2"
tempdir = "0.3"

[[bin]]
name = "pinentry"
test = false

[[test]]
name = "keylist"

[[test]]
name = "encrypt_simple"

[[test]]
name = "encrypt_symmetric"

[[test]]
name = "verify"

[[test]]
name = "edit"

[workspace]
