[package]
name = "gpgme"
description = "GPGme bindings for Rust"
repository = "https://github.com/johnschug/rust-gpgme"
documentation = "https://johnschug.github.io/rust-gpgme"
version = "0.2.0"
authors = ["John Schug <john.ips.schug@gmail.com>"]
license = "LGPL-2.1"
keywords = ["gpg", "gpgme", "crypto", "cryptography"]

[dependencies]
libc = "0.1"
bitflags = "0.1"
enum_primitive = "*"
lazy_static = "0.1"

[dependencies.gpgme-sys]
path = "gpgme-sys"
version = "0.1.1"

[dev-dependencies]
getopts = "0.2"
