[package]
name = "gpgme"
version = "0.8.0"
edition = "2018"
authors = ["John Schug <john.ips.schug@gmail.com>"]
license = "LGPL-2.1"
readme = "README.md"
repository = "https://github.com/gpg-rs/gpgme"
documentation = "https://docs.rs/gpgme"
categories = ["api-bindings"]
keywords = ["gpg", "gpgme", "crypto", "cryptography"]
description = "GPGme bindings for Rust"
autotests = false

[badges]
travis-ci = { repository = "gpg-rs/gpgme" }
maintenance = { status = "experimental" }

[features]
nightly = []

[dev-dependencies]
structopt = "0.2"
tempdir = "0.3"

[dependencies]
libc = "0.2"
bitflags = "1"
once_cell = "0.2"
conv = "0.3"
smallvec = "0.6"
cstr-argument = "0.1"
gpg-error = "0.4"

[dependencies.ffi]
package = "gpgme-sys"
path = "gpgme-sys"
version = "0.8.0"

[patch.crates-io]
gpg-error = { path = "../libgpg-error" }
libgpg-error-sys = { path = "../libgpg-error/libgpg-error-sys" }

[[bin]]
name = "pinentry"
test = false

[[test]]
name = "keylist"

[[test]]
name = "encrypt_simple"

[[test]]
name = "encrypt_symmetric"

[[test]]
name = "verify"

[[test]]
name = "edit"

[[test]]
name = "context"

[[test]]
name = "keysign"

[workspace]
members = ["systest"]
