[package]
name = "gpgme"
version = "0.6.1"
authors = ["John Schug <john.ips.schug@gmail.com>"]
license = "LGPL-2.1"
readme = "README.md"
repository = "https://github.com/johnschug/rust-gpgme"
documentation = "https://docs.rs/gpgme"
categories = ["api-bindings"]
keywords = ["gpg", "gpgme", "crypto", "cryptography"]
description = "GPGme bindings for Rust"

[badges]
travis-ci = { repository = "johnschug/rust-gpgme" }
maintenance = { status = "experimental" }

[features]
nightly = ["lazy_static/nightly"]

[build-dependencies]
semver = "0.8"

[dev-dependencies]
getopts = "0.2"
tempdir = "0.3"

[dependencies]
libc = "0.2"
cfg-if = "0.1"
bitflags = "1"
lazy_static = "0.2"
conv = "0.3"
cstr-argument = "0.0.2"
gpg-error = "0.2"

[dependencies.gpgme-sys]
path = "gpgme-sys"
version = "0.6.1"

[[bin]]
name = "pinentry"
test = false

[[test]]
name = "keylist"

[[test]]
name = "encrypt_simple"

[[test]]
name = "encrypt_symmetric"

[[test]]
name = "verify"

[[test]]
name = "edit"

[workspace]
