[package]
name = "systest"
version = "0.1.0"
edition = "2018"
authors = ["John Schug <john.ips.schug@gmail.com>"]
publish = false

[build-dependencies]
ctest = "0.2.4"

[dependencies]
libc = "0.2"
gpgme-sys = { path = "../gpgme-sys" }
